### ISSUE TITLE
[question]  Как вы реализовали отображение сцены одновременно в VR очках и в браузере?

### ISSUE THREAD

**Issue by Apo-S** [anxolerd/PlannerVR#1]
Здравствуйте, обычно, при нажатии на кнопку "Просмотр в VR" контент отправляется очкам, а в браузере видно только белую сцену, а вас же не так, у вас остается контент в браузере, как это реализовано?

**Comment by anxolerd** [comment]
Здравствуйте,
Прошу прощения, что не ответил раньше.

Не совсем уверен, что понимаю вопрос правильно, но если речь о том, как оно работает в браузере, если нет очков, и в очках, если они есть, то подозреваю, что ответ кроется в библиотеке, которую я использовал, а именно: [react-vr](https://facebook.github.io/react-vr/). В любом случае, насколько я помню, я не писал ничего такого, чтобы явно поддерживать описанное Вами поведение.
